---
version: 3

images:
  base_image:
    name: "quay.io/ansible/awx-ee:latest"

dependencies:
  galaxy: requirements.yml

additional_build_steps:
  prepend_base:
    - RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && alternatives --set python3 /usr/bin/python3.11

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"
